### ISSUE TITLE
Cannot read output channels after 8 channels (probably minor issue?)

### ISSUE THREAD

**Issue by aditi-nethwewala** [levylabpitt/Multichannel-Lockin#21]
The output channels displayed on the Main lockin FP tab only goes upto 8 channels. But we can go to Lockin Display 2 to see all channel outputs

**Comment by ciozi137** [comment]
@aditi-nethwewala can you add a screenshot of which control you mean?

**Comment by aditi-nethwewala** [comment]
![image](https://user-images.githubusercontent.com/61893772/85947216-3bfc5380-b917-11ea-9613-14f218ff301e.png)

**Comment by ciozi137** [comment]
Oh ok perfect. I didn’t know what you meant before. Thanks

**Comment by ciozi137** [comment]
![image](https://user-images.githubusercontent.com/26659428/86012429-f3629a00-b9eb-11ea-9dc4-6b715999a09d.png)
