### ISSUE TITLE
Multiple reference frequency issue

### ISSUE THREAD

**Issue by aditi-nethwewala** [levylabpitt/Multichannel-Lockin#24]
When more than one channel is entered in the reference frequency tab, the output is messed up even if the same frequency is entered

**Comment by ciozi137** [comment]
@aditi-nethwewala do you mean this:
![image](https://user-images.githubusercontent.com/26659428/86003749-3f0f4680-b9e0-11ea-869a-440c3f714962.png)

**Comment by aditi-nethwewala** [comment]
yes

**Comment by ciozi137** [comment]
@aditi-nethwewala  what do you mean by "messed up"?

**Comment by aditi-nethwewala** [comment]
The output values are wrong. @Yh-lab  can show you when you log in to PPMS I think

**Comment by ciozi137** [comment]
v2.10.1.23
