### ISSUE TITLE
Cannot Retrieve Sweep Results

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/Multichannel-Lockin#56]
I am having issues with getting the data back out of the Lockin program. I checked through the source code of the Lockin Program and everything seemed fine as far as I can tell. I will also put this as an issue on github as well. This is what the most bare bones test code I am using looks like:
![image](https://user-images.githubusercontent.com/37567672/170584801-8fbe57df-f5fe-45d3-8d13-14095bc90311.png)

![image](https://user-images.githubusercontent.com/37567672/170584826-adc00681-de03-4a84-baaa-338da3075d24.png)
Beyond not getting any results back, getSweepResults also takes a really long time, 24 seconds exactly, and it seems like it is timing out.

So I did some digging in the source code and figure it might be helpful to review the entire process of the sequence...

So the first part is when the DAQ process is finished with the sweep, it will call the state Sweep: Stop, where it publishes the results using the public event "getSweepWaveforms"
![image](https://user-images.githubusercontent.com/37567672/170584843-fdac8199-3980-4c9c-a4be-2692753ee2c3.png)

This is caught in the Lockin Process which then makes a call to its parent, the Instrument Process.
![image](https://user-images.githubusercontent.com/37567672/170584866-4ac29e0a-0396-42db-978e-57487e66ffeb.png)

It uses the command setData_SweepWaveforms.

In the instrument process, this is handled by the "Instrument: Handle Local Command" state which itself calls on "HandleCommand.vi"
It seems like a fairly straightforwards unflattening and bundling of data:
![image](https://user-images.githubusercontent.com/37567672/170584887-9a8a973e-2cab-426c-99ec-e0660c0eadd9.png)

So then when we do the API call it calls the command "getSweepWaveforms" right to the Instrument Process
![image](https://user-images.githubusercontent.com/37567672/170584903-9bd8d361-11f4-4b3e-b647-6269add64f3e.png)

This is eventually sent to the "Instrument: Handle Remote Command" state where it calls on "HandleCommand.vi" where it just gets the values
![image](https://user-images.githubusercontent.com/37567672/170584938-327c7188-ceac-46a2-8464-ddb1130e2fa5.png)

and then sends it on its way:
![image](https://user-images.githubusercontent.com/37567672/170584951-3057628e-f6ea-47f0-a9ca-fc8570f55081.png)

So everything looks good so I'm not sure what the issue is exactly. Furthermore, getAI seems to work fine, it's just getSweepResults...

**Comment by Monkeymerlot** [comment]
Putting it in debug mode it seems that the message is actually sent but is just not received.
![image](https://user-images.githubusercontent.com/37567672/170587398-b5b27e6c-d045-4983-94b3-fce0d64e3e2e.png)

**Comment by Monkeymerlot** [comment]
It works when I use these settings:
![image](https://user-images.githubusercontent.com/37567672/170589494-199591d2-190f-4e14-8a86-ecfe5760a338.png)

but not with these settings:
![image](https://user-images.githubusercontent.com/37567672/170589622-9bd4abf3-b943-45f3-978d-42d13b99f2a8.png)

**Comment by Monkeymerlot** [comment]
I halved Fs, #s, and then doubled the time of the IV sweep (which would have caused it to not work before) and it worked this time around.

**Comment by ciozi137** [comment]
Quick calculation:

http://www.wolframalpha.com/input/?i=6500%20samples%2Fsecond%2Fchannel%2A6%20seconds%2A64%20bits%2Fsample%2Fchannel%2A8%20channels%2A4%20channels

Doesn’t seem outrageous. I’m not sure the size once the data is flattened to a string.

![image](https://user-images.githubusercontent.com/26659428/170609935-b5a1bfcf-058d-4221-875f-c81014b9bc2a.jpeg)

**Comment by Monkeymerlot** [comment]
Flatten to string is essentially typecasting to a string. It should not affect the size by any appreciable amount.

**Comment by ciozi137** [comment]
Look in Users\…\AppData\Levylab\error logs\multichannel lockin\

**Comment by Monkeymerlot** [comment]
So there are 4 files from today all are basically identical to this one:
[2022-05-26 181912 Errors.txt](https://github.com/levylabpitt/Multichannel-Lockin/files/8783483/2022-05-26.181912.Errors.txt)

**Comment by ciozi137** [comment]
Interesting. That's coming from an unrelated module.  Seemingly. I'll have to think about this

**Comment by Monkeymerlot** [comment]
OK Let me know if you need any help with anything.

**Comment by ciozi137** [comment]
@Monkeymerlot on my virtual machine I am able to sweep 6" at 6500 S/s with 16 channels:
(6,500 S/s )(6 s)(16 channels)(4 channel types [AO/AI/X/Y]))(64 bits/S) = 19 MB

**Comment by ciozi137** [comment]
@Monkeymerlot we discovered there was a timeout error that was preventing the message from being transmitted when the message is larger than ~10 MB. Short term fix is to increase the timeout. Longer term I need to look into the Lazy Pirate protocol, or look into the message format (perhaps transmit in chunks or multipart, idk)
