### ISSUE TITLE
Sweep Input Wave Strange Behavior

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/Multichannel-Lockin#61]
I have a 10 kOhm resistor for a test and I get the following input:
![image](https://user-images.githubusercontent.com/37567672/173133921-69cde848-08e0-4116-b10e-c1c83c07539b.png)
so the values look right but the waveform is cut off and there is a section at the beginning. 

Removing the initial wait and changing total time to 10s (and hitting refresh):
![image](https://user-images.githubusercontent.com/37567672/173134238-2157f013-29b1-470a-9176-631c6d851fdc.png)

Switch to Ramp / from Ramp/\:
![image](https://user-images.githubusercontent.com/37567672/173134865-77d830c8-cf02-4af4-8ae2-324aae9c85f4.png)

Change time of sweep to 3s from 10s:
![image](https://user-images.githubusercontent.com/37567672/173134963-b4df97f2-068b-4fe2-afa2-5510ca4edc8e.png)

**Comment by ciozi137** [comment]
@Monkeymerlot thanks

**Comment by Monkeymerlot** [comment]
Still looks like there is a bit of offset between the two.
![image](https://user-images.githubusercontent.com/37567672/174408349-5de5a881-4610-49c5-965a-369662f3de94.png)

**Comment by ciozi137** [comment]
@Monkeymerlot try making #s 2x or 4x bigger

**Comment by Monkeymerlot** [comment]
It looks better now. N = 2250 and Fs = 2500. 500 MΩ resistor.
![image](https://user-images.githubusercontent.com/37567672/174409693-a183f031-86a9-473f-9602-446fc01f2a18.png)

**Comment by ciozi137** [comment]
Looks great. By increases #s you decrease the update rate. I think if it's too fast then there will be dropped points. I would like to get a better handle on that and take it out of the end users' hands
