### ISSUE TITLE
Arbitrary Sweep Waveforms

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/Multichannel-Lockin#63]
It would be nice to be able to put in arbitrary waveforms for sweeps.
![image](https://user-images.githubusercontent.com/37567672/175102982-c45af903-a52b-48d8-9855-27ddd051513d.png)

For IV curves, it is common to do stuff like this:
![image](https://user-images.githubusercontent.com/37567672/175101669-e3de01ad-08ab-44ca-a437-09a91e451619.png)

**Comment by ciozi137** [comment]
I like it

**Comment by ciozi137** [comment]
@Monkeymerlot regarding sweep waveforms, do you want **x** to be time? samples?

**Comment by Monkeymerlot** [comment]
I think either one of them is fine since it is possible to retrieve the sampling settings, it would be easy to just convert over on the user's side to either.

**Comment by ciozi137** [comment]
Oh right I forgot that waveforms contain the sampling info...

**Comment by ciozi137** [comment]
@Monkeymerlot more questions:
Right now the sweep mode has a parameter "sweep time" = T_S
- Do you think the arbitrary waveform should define/override T_S?
  - The duration of the waveform would define T_S. 
- Or, should the lock-in just expand and interpolate the arbitrary waveform as defined by "sweep time"?
  - dt of the arbitrary waveform would be ignored
  - For example, you could send an arbitrary waveform with only 9 points, like in your figure, but the lock-in would interpolate to make it sweep for the duration T_S (interpolates to have T_S*Fs samples).

**Comment by ciozi137** [comment]
I think I prefer option 2, however in the case of a frequency sweep the frequency would not be well-defined.

I could make it dynamic in the sense if you give it a m waveform datatype the program would use that dt (ie _setSweepWaveform_) and there could be another command for sending a pattern/1D array to be interpolated (ie _setSweepPattern_)

**Comment by ciozi137** [comment]
I think that it could be problematic to take dt from the setSweepWaveforms. If the user gives two waveforms with different lengths or dt there will be a problem. T_S will be the master sweep duration for all channels, and any waveforms will be interpolated to conform

**Comment by Monkeymerlot** [comment]
@ciozi137 To use this, do we just set the voltages in the table array, and then set the total time for running in the Sweep time?
![image](https://user-images.githubusercontent.com/37567672/191831418-fc2c29bb-8243-4875-8dd0-dc1b37e01638.png)

**Comment by ciozi137** [comment]
@Monkeymerlot that is correct. I will record a short video tutorial

**Comment by Monkeymerlot** [comment]
OK I can make a page in the wiki as well once I finish updating the changes to the lithography plugin/program.

**Comment by ciozi137** [comment]
@Monkeymerlot [13 minutes] https://drive.google.com/file/d/1dsQERQ9ueWCW3XkIxUuyW4XUpCRtKbS_/view?usp=drivesdk

**Comment by Monkeymerlot** [comment]
@ciozi137 The utility for setting the table looks fantastic.
