### ISSUE TITLE
[QCoDeS] Issue with controller label encoding for AO Phase.

### ISSUE THREAD

**Issue by pgwijesinghe** [levylabpitt/Multichannel-Lockin#84]
Upon parsing the message to change AO Phase from Python to LabVIEW, there's an encoding issue with handling the "°" symbol. In the next release, we'll need to change the label of the phase control to something like "Phase (deg)" in the typedef.
![image](https://github.com/user-attachments/assets/3595180c-4215-4397-9a40-18aaf225098d)

**Comment by ciozi137** [comment]
Agree. I am also interested in representing the units in another way. Changing to deg is definitely a simple first step
